CREATE DATABASE stocksmds;

CREATE SCHEMA stocksmds.common;

CREATE TABLE bronze_stocks_quotes_raw(
v VARIANT
)

SELECT * FROM STOCKSMDS.COMMON.BRONZE_STOCKS_QUOTES_RAW

SELECT * FROM STOCKSMDS.COMMON.BRONZE_STG_STOCKS_QUOTES

SELECT * FROM STOCKSMDS.COMMON.SILVER_CLEAN_STOCKS_QUOTES

SELECT * FROM STOCKSMDS.COMMON.GOLDTREECHART

SELECT * FROM STOCKSMDS.COMMON.GOLD_CANDLESTICK

SELECT * FROM STOCKSMDS.COMMON.GOLD_KPI